Bulk improvements; fish, nspawn

diff --git a/.local/bin/zigup b/.local/bin/zigup
--- a/.local/bin/zigup
+++ b/.local/bin/zigup
@@ -21,7 +21,7 @@ die() { msg "$@"; exit 1; }
 
 mkdir -p "${TMP_DIR}"
 
-test -d "${ROOT_DIR}" || die "Root directory \"${ROOT_DIR}\" does not exist!"
+test -d "${ROOT_DIR}" || die "Directory \"${ROOT_DIR}\" does not exist!"
 type curl >/dev/null 2>&1 || die "curl is required but not available!"
 type jq >/dev/null 2>&1 || die "jq is required but not available!"
 type shasum >/dev/null 2>&1 || die "shasum is required but not available!"
@@ -52,10 +52,10 @@ else
   ln -s "${version}" "${ROOT_DIR}/zig-latest" || die "Failed to set new symlink!"
   ln -s zig-latest/zig "${ROOT_DIR}/zig_" || die "Failed to set new symlink!"
 
-  # Clean up old versions; keep the last 5 downloads                             
+  # Clean up old versions; keep the last 5 downloads
   find "${ROOT_DIR}"/zig-linux-x86_64-* -prune | head -n -5 | while IFS='' read -r path; do
-    rm -r "$path"                                                                          
-  done                                                                                     
-fi                                                                                         
-                 
+    rm -r "$path"
+  done
+fi
+
 msg "Current version: $("${ROOT_DIR}/zig-latest/zig" version)"
